### ISSUE TITLE
Ran into compiling issue - need to install ProtoBuf 

### ISSUE THREAD

**Issue by gzhang8** [UCM-MESA/mav-visual-stabilizer#1]
Ran into compiling issue - need to install ProtoBuf (see https://gist.github.com/samklr/0b8a0620f82005e7f556)

MAVROS https://github.com/UCM-ME190/MavRos-takeoff-n-land Ran into compiling issue - need to install ProtoBuf (see https://gist.github.com/samklr/0b8a0620f82005e7f556)

@mchen0037 Let's use Issue to track problems. Did you solved it or not?

**Comment by mchen0037** [comment]
Yes, installing the 2.6.1 version of ProtoBuf allowed Gazebo to run for the quadcopter.
